#include "FactoryContent.h"

#include <BinaryData.h>
#include <io/AudioFileIO.h>

namespace tf::app {

const std::vector<FactorySound>& factorySounds()
{
    // Generated by tools/scripts/make_samples.py: original sounds, no third-party audio.
    static const std::vector<FactorySound> sounds {
        { "Glass", "Tonal", "glass_wav", 81 },
        { "Singing bowl", "Tonal", "bowl_wav", 57 },
        { "Kalimba", "Tonal", "kalimba_wav", 72 },
        { "Felt piano", "Tonal", "felt_piano_wav", 60 },
        { "Marimba", "Tonal", "marimba_wav", 60 },
        { "Bell", "Tonal", "bell_wav", 69 },
        { "Pluck", "Tonal", "pluck_wav", 50 },
        { "Chord", "Pad", "chord_wav", 50 },
        { "Choir", "Pad", "choir_wav", 50 },
        { "Bowed strings", "Pad", "bowed_strings_wav", 38 },
        { "Harmonium", "Pad", "harmonium_wav", 60 },
        { "Sub organ", "Pad", "sub_organ_wav", 38 },
        { "Shimmer", "Pad", "shimmer_wav", 74 },
        { "Wind chimes", "Texture", "wind_chimes_wav", -1 },
        { "Breath", "Texture", "breath_wav", -1 },
        { "Ocean", "Texture", "ocean_wav", -1 },
        { "Rain on leaves", "Texture", "rain_leaves_wav", -1 },
        { "Tape dust", "Texture", "tape_dust_wav", -1 },
    };
    return sounds;
}

std::shared_ptr<const dsp::SampleBuffer> loadFactorySound(const FactorySound& sound)
{
    int size = 0;
    const char* data = BinaryData::getNamedResource(sound.resource, size);
    if (data == nullptr || size <= 0)
        return nullptr;
    juce::String error;
    auto b = io::loadSample(std::make_unique<juce::MemoryInputStream>(data, static_cast<size_t>(size), false), sound.name, error);
    return std::shared_ptr<const dsp::SampleBuffer>(std::move(b));
}

namespace {

const FactorySound* findSound(const char* name)
{
    for (const auto& s : factorySounds())
        if (juce::String(s.name) == name)
            return &s;
    return nullptr;
}

io::SessionData::SceneData scene(const char* name, float x, float y, std::map<std::string, float> values)
{
    io::SessionData::SceneData s;
    s.name = name;
    s.x = x;
    s.y = y;
    s.values = std::move(values);
    return s;
}

} // namespace

io::SessionData makeStarterSession(const engine::Engine& engine)
{
    auto s = io::defaultSession(engine);

    // Material: a choir in Cloud 1, the singing bowl in Cloud 2, glass in Bloom.
    if (const auto* choir = findSound("Choir"))
        if (auto b = loadFactorySound(*choir))
            s.samples["cloud1"] = b;
    if (const auto* bowl = findSound("Singing bowl"))
        if (auto b = loadFactorySound(*bowl))
            s.samples["cloud2"] = b;
    if (const auto* glass = findSound("Glass"))
        if (auto b = loadFactorySound(*glass))
        {
            s.samples["bloom"] = b;
            s.params["bloom.root"] = static_cast<float>(glass->rootNote);
        }
    s.params["cloud2.level"] = -60.0f; // the scenes bring it in

    // Six places, each a different weather of the same piece. Every scene names the
    // same parameters so the terrain blends smoothly between all of them.
    // Top: open and bright; bottom: deep and dark. Left: still; right: active.
    s.scenes = {
        scene("Still", 0.18f, 0.78f, { { "drone.cutoff", 700.0f }, { "drone.density", 2.0f }, { "drone.level", -4.0f }, { "drone.noise", 0.05f },
                                       { "cloud1.density", 5.0f }, { "cloud1.grainMs", 700.0f }, { "cloud1.spray", 0.1f }, { "cloud1.level", -6.0f },
                                       { "cloud2.level", -60.0f }, { "cloud2.density", 4.0f }, { "res.rain", 0.05f }, { "res.level", -14.0f },
                                       { "weather.wind", 0.0f }, { "weather.rain", 0.0f }, { "weather.surf", 0.0f }, { "medium.drive", 0.2f },
                                       { "tide.rate", 0.6f }, { "drone.sendA", -12.0f } }),
        scene("Dawn", 0.5f, 0.86f, { { "drone.cutoff", 1600.0f }, { "drone.density", 3.0f }, { "drone.level", -3.0f }, { "drone.noise", 0.12f },
                                     { "cloud1.density", 14.0f }, { "cloud1.grainMs", 320.0f }, { "cloud1.spray", 0.3f }, { "cloud1.level", -3.0f },
                                     { "cloud2.level", -14.0f }, { "cloud2.density", 6.0f }, { "res.rain", 0.18f }, { "res.level", -8.0f },
                                     { "weather.wind", 0.08f }, { "weather.rain", 0.0f }, { "weather.surf", 0.0f }, { "medium.drive", 0.25f },
                                     { "tide.rate", 1.0f }, { "drone.sendA", -10.0f } }),
        scene("Glass rain", 0.84f, 0.74f, { { "drone.cutoff", 2600.0f }, { "drone.density", 3.0f }, { "drone.level", -10.0f }, { "drone.noise", 0.1f },
                                            { "cloud1.density", 30.0f }, { "cloud1.grainMs", 120.0f }, { "cloud1.spray", 0.6f }, { "cloud1.level", -8.0f },
                                            { "cloud2.level", -6.0f }, { "cloud2.density", 18.0f }, { "res.rain", 0.7f }, { "res.level", -3.0f },
                                            { "weather.wind", 0.05f }, { "weather.rain", 0.3f }, { "weather.surf", 0.0f }, { "medium.drive", 0.3f },
                                            { "tide.rate", 1.6f }, { "drone.sendA", -8.0f } }),
        scene("Tidepool", 0.5f, 0.48f, { { "drone.cutoff", 1100.0f }, { "drone.density", 4.0f }, { "drone.level", -4.0f }, { "drone.noise", 0.15f },
                                         { "cloud1.density", 22.0f }, { "cloud1.grainMs", 200.0f }, { "cloud1.spray", 0.45f }, { "cloud1.level", -4.0f },
                                         { "cloud2.level", -10.0f }, { "cloud2.density", 10.0f }, { "res.rain", 0.35f }, { "res.level", -6.0f },
                                         { "weather.wind", 0.1f }, { "weather.rain", 0.1f }, { "weather.surf", 0.25f }, { "medium.drive", 0.3f },
                                         { "tide.rate", 1.2f }, { "drone.sendA", -12.0f } }),
        scene("Deep water", 0.18f, 0.2f, { { "drone.cutoff", 320.0f }, { "drone.density", 5.0f }, { "drone.level", 0.0f }, { "drone.noise", 0.2f },
                                           { "cloud1.density", 6.0f }, { "cloud1.grainMs", 1100.0f }, { "cloud1.spray", 0.2f }, { "cloud1.level", -8.0f },
                                           { "cloud2.level", -60.0f }, { "cloud2.density", 3.0f }, { "res.rain", 0.02f }, { "res.level", -20.0f },
                                           { "weather.wind", 0.0f }, { "weather.rain", 0.0f }, { "weather.surf", 0.45f }, { "medium.drive", 0.35f },
                                           { "tide.rate", 0.4f }, { "drone.sendA", -16.0f } }),
        scene("Storm", 0.84f, 0.2f, { { "drone.cutoff", 900.0f }, { "drone.density", 6.0f }, { "drone.level", -2.0f }, { "drone.noise", 0.55f },
                                      { "cloud1.density", 70.0f }, { "cloud1.grainMs", 90.0f }, { "cloud1.spray", 0.85f }, { "cloud1.level", -6.0f },
                                      { "cloud2.level", -12.0f }, { "cloud2.density", 40.0f }, { "res.rain", 0.55f }, { "res.level", -8.0f },
                                      { "weather.wind", 0.65f }, { "weather.rain", 0.55f }, { "weather.surf", 0.2f }, { "medium.drive", 0.6f },
                                      { "tide.rate", 2.4f }, { "drone.sendA", -8.0f } }),
    };
    s.params["terrain.x"] = 0.5f;
    s.params["terrain.y"] = 0.62f;
    return s;
}

} // namespace tf::app
